### ISSUE TITLE
Can't parse AIDL interfaces

### ISSUE THREAD

**Issue by anonymix007** [tardyp/rs-bp#1]
File:
```
package {
    default_applicable_licenses: ["Android-Apache-2.0"],
}

aidl_interface {
    name: "android.hardware.tetheroffload",
    vendor_available: true,
    srcs: ["android/hardware/tetheroffload/*.aidl"],
    stability: "vintf",
    backend: {
        cpp: {
            enabled: false,
        },
        java: {
            sdk_version: "module_current",
            apex_available: [
                "com.android.tethering",
            ],
            min_sdk_version: "30",
            enabled: true,
        },
        ndk: {
            apps_enabled: false,
        },
    },
    versions_with_info: [
        {
            version: "1",
            imports: [],
        },
    ],
    frozen: true,

}
```
Error:
```
./Android.bp: 0: at line 27, in Tag:
        {
        ^

1: at line 26, in array:
    versions_with_info: [
                        ^

2: at line 26, in value:
    versions_with_info: [
                        ^

3: at line 25, in module entry:
    },
      ^

4: at line 5, in module:
aidl_interface {
               ^

5: at line 1, in blueprint:
package {
^


thread 'main' panicked at examples/parse_all.rs:33:25:
please report! this file is not parsed correctly
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by anonymix007** [comment]
Another one:
```
soong_config_module_type {
    name: "qtidisplay_cc_defaults",
    module_type: "cc_defaults",
    config_namespace: "qtidisplay",
    bool_variables: [
        "drmpp",
        "headless",
        "llvmsa",
        "gralloc4",
        "gralloc_handle_has_no_reserved_size",
        "default",
        "var3",
        "llvmcov",
        "panel_dimension_extra_precision",
    ],
    properties: [
        "cflags",
        "enabled",
        "srcs",
        "header_libs",
        "host_ldlibs",
        "ldflags",
        "native_coverage",
	"vendor",
    ],
}

soong_config_module_type {
	name: "qtidisplay_prebuilt_defaults",
	module_type: "cc_defaults",
	config_namespace: "qtidisplay",
	bool_variables: [
		"var1",
		"var2",
		"var3",
	],
	properties: [
		"enabled",
	],
}

qtidisplay_prebuilt_defaults {
	name: "qtidisplay_prebuilt_var1_defaults",
	soong_config_variables: {
		var1 : {
			enabled: true,
			conditions_default: {
				enabled: false,
			},
		},
	},
}

qtidisplay_prebuilt_defaults {
	name: "qtidisplay_prebuilt_var2_defaults",
	soong_config_variables: {
		var2 : {
			enabled: true,
			conditions_default: {
				enabled: false,
			},
		},
	},
}

qtidisplay_prebuilt_defaults {
	name: "qtidisplay_prebuilt_var3_defaults",
	soong_config_variables: {
		var3 : {
			enabled: true,
			conditions_default: {
				enabled: false,
			},
		},
	},
}


qtidisplay_cc_defaults {
    name: "qtidisplay_common_defaults",
    cflags: [
        "-Wno-missing-field-initializers",
        "-Wall",
        "-Werror",
    ],
    shared_libs: [
        "liblog",
        "libcutils",
        "libutils",
    ],
    soong_config_variables: {
        drmpp: {
            cflags: ["-DPP_DRM_ENABLE"],
        },
        headless: {
            cflags: ["-DTARGET_HEADLESS", "-DQMAA"],
        },
        llvmsa: {
            cflags: [
                "--compile-and-analyze",
                "--analyzer-perf",
            ],
        },
        gralloc4: {
            cflags: ["-DTARGET_USES_GRALLOC4"],
        },
        var3 : {
            enabled: false,
            conditions_default: {
                enabled: true,
            },
        },
        panel_dimension_extra_precision: {
            cflags: ["-DTARGET_PANEL_DIMENSION_HAS_EXTRA_PRECISION"],
        },
        gralloc_handle_has_no_reserved_size: {
            cflags: ["-DGRALLOC_HANDLE_HAS_NO_RESERVED_SIZE"],
        },
    },
}

qtidisplay_cc_defaults {
    name: "qtidisplay_defaults",
    defaults: ["qtidisplay_common_defaults"],
    soong_config_variables: {
        default: {
            header_libs: ["display_headers", "qti_kernel_headers"],
        },
        headless: {
            header_libs: ["display_headers"],
            enabled: false,
            conditions_default: {
                enabled: true,
            },
        },
        llvmcov: {
            cflags: [
                "-Wl",
                "-fprofile-instr-generate",
                "-fcoverage-mapping",
                "-fprofile-instr-append-file",
                "-DPROFILE_COVERAGE_DATA",
            ],

            ldflags: [
                "-fcoverage-mapping",
                " -fprofile-instr-generate",
                "-fuse-ld=lld",
                "-gline-tables-only",
                "-fdebug-info-for-profiling",
            ],
            vendor: true,
            host_ldlibs: ["-lgcov"],
            native_coverage: true,
        },
    },
}

qtidisplay_cc_defaults {
    name: "qtidisplay_alloc_defaults",
    defaults: ["qtidisplay_common_defaults"],
    soong_config_variables: {
        llvmcov: {
            cflags: [
                "-Wl",
                "-fprofile-instr-generate",
                "-fcoverage-mapping",
                "-fprofile-instr-append-file",
                "-DPROFILE_COVERAGE_DATA"
            ],

            ldflags: [
                "-fcoverage-mapping",
                " -fprofile-instr-generate",
                "-fuse-ld=lld",
                "-gline-tables-only",
                "-fdebug-info-for-profiling",
            ],
            vendor: true,
            host_ldlibs: ["-lgcov"],
            native_coverage: true,
        },
    },
}

qtidisplay_cc_defaults {
    name: "qti_qmaa_display_defaults",
    defaults: ["qtidisplay_common_defaults"],
    header_libs: ["qmaa_display_headers"],
}

qtidisplay_cc_defaults {
    name: "qtidisplay_coverage_defaults",
    soong_config_variables: {
        llvmcov: {
            cflags: [
                "-Wl",
                "-fprofile-instr-generate",
                "-fcoverage-mapping",
                "-fprofile-instr-append-file",
                "-DPROFILE_COVERAGE_DATA"
            ],

            ldflags: [
                "-fcoverage-mapping",
                " -fprofile-instr-generate",
                "-fuse-ld=lld",
                "-gline-tables-only",
                "-fdebug-info-for-profiling",
            ],
            vendor: true,
            host_ldlibs: ["-lgcov"],
            native_coverage: true,
        },
    },
}

cc_library_headers {
    name: "display_debug_headers",
    vendor: true,
    export_include_dirs: [
        "libdebug",
    ],
}

cc_library_headers {
    name: "display_headers",
    vendor: true,
    export_include_dirs: [
        "include",
        "libdrmutils",
        "libqdutils",
        "libqservice",
        "gpu_tonemapper",
        "sdm/include",
        "gralloc",
        "libhistogram",
    ],
    header_libs: [
        "libhardware_headers",
        "display_intf_headers",
        "display_debug_headers",
    ],
    export_header_lib_headers: [
        "libhardware_headers",
        "display_intf_headers",
        "display_debug_headers",
    ],
}

cc_library_headers {
    name: "qmaa_display_headers",
    vendor: true,
    export_include_dirs: [

    ],
    header_libs: [
        "display_debug_headers",
    ],
    export_header_lib_headers: [
        "display_debug_headers",
    ],
}

subdirs = [
    "init",
    "libqservice",
    "libqdutils",
    "libddebug",
    "libdrmutils",
    "libhistogram",
    "liblight",
    "composer",
    "gralloc",
    "gpu_tonemapper",
    "hdmi_cec",
    "sde-drm",
    "sdm/libs/utils",
    "sdm/libs/core",
    "qmaa",
    "oem_services",
]
```
Error:
```
soong_config_module_type Some(String("qtidisplay_cc_defaults"))
soong_config_module_type Some(String("qtidisplay_prebuilt_defaults"))
qtidisplay_prebuilt_defaults Some(String("qtidisplay_prebuilt_var1_defaults"))
qtidisplay_prebuilt_defaults Some(String("qtidisplay_prebuilt_var2_defaults"))
qtidisplay_prebuilt_defaults Some(String("qtidisplay_prebuilt_var3_defaults"))
qtidisplay_cc_defaults Some(String("qtidisplay_common_defaults"))
qtidisplay_cc_defaults Some(String("qtidisplay_defaults"))
qtidisplay_cc_defaults Some(String("qtidisplay_alloc_defaults"))
qtidisplay_cc_defaults Some(String("qti_qmaa_display_defaults"))
qtidisplay_cc_defaults Some(String("qtidisplay_coverage_defaults"))
cc_library_headers Some(String("display_debug_headers"))
cc_library_headers Some(String("display_headers"))
cc_library_headers Some(String("qmaa_display_headers"))
/home/user/aosp/hardware/qcom/display/composer/Android.bp: 0: at line 22, in Tag:
        "-DLOG_TAG=\"SDM\"",
                     ^

1: at line 19, in array:
    cflags: [
            ^

2: at line 19, in value:
    cflags: [
            ^

3: at line 17, in module entry:
    ],
      ^

4: at line 3, in module:
cc_binary {
          ^

5: at line 1, in blueprint:
composer_srcs = ["*.cpp"]
^


thread 'main' panicked at examples/parse_all.rs:33:25:
please report! this file is not parsed correctly
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by tardyp** [comment]
thanks for the report. Sorry for the delay. I missed the mail. I will look at it.
